version: '3.9'

networks:
  smart-finance-ai-network:
    driver: bridge
    
# docker compose up -d db-service
services:
  db-service:
    container_name: mysql-smart-finance-ai
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - smart-finance-ai-network

# docker compose up -d ml-service
  ml-service:
    container_name: ml-service
    build:
      context: .
      dockerfile: docker/ml-api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ML_API_KEY=${ML_API_KEY}
      - OCI_STORAGE_BUCKET=smart-finance-ai-bucket
    networks:
      - smart-finance-ai-network

# docker compose up -d backend-service
  backend-service:
    container_name: backend-service
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db-service:3306/${MYSQL_DB}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ML_SERVICE_URL=http://ml-service:8000
      - ML_API_KEY=${ML_API_KEY}
    depends_on:
      ml-service:
        condition: service_started
      db-service:
        condition: service_healthy
    networks:
      - smart-finance-ai-network

  #frontend-service:
  #  container_name: frontend-service
  #  build:
   #   context: .
   #   dockerfile: docker/frontend.Dockerfile
   # ports:
   #   - "80:80"
  #  depends_on:
   #   - backend-service
  #  networks:
   #   - smart-finance-ai-network

volumes:
  mysql_data: